export const categoriesMaster = [
    'Accommodations - Long Term',
    'Accommodations - Short Term',
    'Accompianist',
    'Accountant',
    'Acting Coach',
    'Agent-Screen',
    'Agent-Theatre',
    'Art School',
    'Audio/Visual Services',
    'Audition Services',
    'Backdrops',
    'Broadway Workshop',
    'Camp',
    'Cobbler',
    'Costume Rental',
    'Costumer',
    'Craft Services/Catering',
    'Dance School',
    'Demo Reels',
    'Dentist',
    'Dialect Coach',
    'Dramaturg',
    'Editing Services',
    'Entertainment Attorney',
    'Equipment Rental',
    'Film Festival',
    'Film School',
    'Fundraising',
    'Grant Writer',
    'Graphic Designer',
    'Guitar Instruction',
    'Hair Stylist',
    'Make Up Artist',
    'Music School',
    'Photographer',
    'Piano Instruction',
    'Private Dance Instruction',
    'Production Company',
    'Recording Studio',
    'Rehearsal Space',
    'Saxophone Instruction',
    'Set Medic/RN',
    'Set Teacher/Tutor',
    'Special FX Artist',
    'Spray Tan',
    'Stunt Training',
    'Summer Camp/Program',
    'Tailor/Seamstress',
    'Talent Managers',
    'Theatre',
    'Training Center',
    'Vocal Coach',
    'Wig Maker',
];


export const countries = [
    'Australia',
    'China',
    'India',
    'Mexico',
    'United Kingdom',
    'United States',
];


export const sportsMaster = [
    'Aerobics',
    'Archery',
    'Badminton',
    'Baseball',
    'Basketball',
    'Baton Twirling',
    'Billiards/Pool Player',
    'Boating - engine',
    'Boating - Sail',
    'Body Building',
    'Body Surfing',
    'Bowling',
    'Boxing',
    'Canoeing',
    'Cheerleading',
    'Combat - Actual Service',
    'Combat - Stage',
    'Cricket',
    'Cycling',
    'Cycling - Mountain Biking',
    'Cycling - Unicycle',
    'Diving',
    'Equestrian - Dressage',
    'Equestrian - English',
    'Equestrian - General',
    'Equestrian - Racing',
    'Equestrian - Reining',
    'Equestrian - Rodeo',
    'Equestrian - Show Jumping',
    'Equestrian - Western',
    'Fencing',
    'Figure Skating',
    'Fishing',
    'Fly Fishing',
    'Football',
    'Frisbee',
    'Golf',
    'Gymnastics',
    'Hackey Sack',
    'Handball',
    'Hang Gliding',
    'Ice Hockey',
    'Hula Hoop',
    'Ice Skating',
    'Jet Skier',
    'Jockey',
    'Jump Rope',
    'Jump Rope - Double Dutch',
    'Karate - Goju-Ryu',
    'Karate - Kenpo',
    'Karate - Shito-Ryu',
    'Karate - Kung Fu',
    'Karate - Shotokan',
    'Karate: Wado-Ryu',
    'Kayaker',
    'Kick Boxing',
    'Kickboxing',
    'Lifeguard',
    'Lacrosse',
    'Martial Arts',
    'Martial Arts - Aikido',
    'Martial Arts - Hapkido',
    'Martial Arts - Jiu-Jitsu',
    'Martial Arts - Jujutsu',
    'Martial Arts - Judo',
    'Martial Arts - Katana',
    'Martial Arts - Kendo',
    'Martial Arts - Kobudo',
    'Martial Arts - Mixed',
    'Martial Arts - Sumo',
    'Martial Arts - Taekwondo',
    'Martial Arts - Tai Chi',
    'Motorcycle Riding - General',
    'Mountain Climbing',
    'Parkour',
    'Pilot - Balloonist',
    'Pilot - Glider',
    'Pilot - Helicopter',
    'Pilot - Single Engine',
    'Pilot - Twin and/or Jet',
    'Ping Pong',
    'Pogo Stick',
    'Racquetball',
    'Rappelling',
    'Rock Climber',
    'Rodeo - Bull Riding',
    'Roller Hockey',
    'Roller Skating',
    'Rollerblading',
    'Rugby',
    'Running - General',
    'Running - Long Distance',
    'Running - Sprint',
    'Sailing',
    'Sailor',
    'Scuba Diver',
    'Scuba Diving',
    'Sculling',
    'Segway',
    'Shooting - Revolver/Automatic',
    'Shooting - Rifle',
    'Shooting - Skeet/Trap',
    'Skateboard - slalom',
    'Skateboard - street',
    'Skateboard - stunts',
    'Skateboarding',
    'Sky Diving',
    'Snorkeling',
    'Snow Skiing - Competition',
    'Snow Skiing - Cross Country',
    'Snow Skiing - Downhill',
    'Snow Skiing - General',
    'Snowboarding',
    'Snowmobile',
    'Soccer',
    'Softball',
    'Speed Skating - ice',
    'Squash',
    'Surfing',
    'Swimming - ability - general',
    'Swimming - backstroke',
    'Swimming - breast stroke',
    'Swimming - butterfly',
    'Swimming - diving',
    'Swimming - freestyle',
    'Swimming - Synchronized',
    'Tennis',
    'Track & Field',
    'Trampoline',
    'Volleyball',
    'Water Skiing',
    'Weight Lift',
    'Wind Surfing',
    'Wrestling',
    'Yoga'
];

export const performanceMaster = [
    'Accordion',
    'Acoustic Bass',
    'Auctioneer',
    'Audio Prompter',
    'Autoharp',
    'Bagpipes',
    'Banjo',
    'Bartender - Vegas Style Flair',
    'Bassoon',
    'Bones',
    'Bongos',
    'Brass Instruments',
    'Cello',
    'Chef',
    'Chef - Garde Manger',
    'Chef - Pastry',
    'Chef - Saucier',
    'Chef - Sous',
    'Clarinet',
    'Clowning',
    'Comedian',
    'Conga',
    'Dance - Bhangara',
    'Dance - Breakdance',
    'Dance - Pole Dancing',
    'Dance Acro',
    'Dance Argentine Tango',
    'Dance Ballet',
    'Dance Ballroom',
    'Dance Belly',
    'Dance Bolero',
    'Dance Cha Cha',
    'Dance Flamenco',
    'Dance Hip Hop',
    'Dance Jazz',
    'Dance Line/Country',
    'Dance Mambo',
    'Dance Modern',
    'Dance Salsa',
    'Dance Rumba',
    'Dance Samba',
    'Dance Swing',
    'Dance Tap',
    'Dance Tango',
    'Dancer',
    'Disc Jockey',
    'Diving',
    'Drums',
    'Dulcimer',
    'Ear Prompter',
    'Fiddle',
    'Firearms',
    'Flute',
    'French Horn',
    'Guitar',
    'Guitar Bass',
    'Harmonica',
    'Host',
    'Impressionist',
    'Improvisation',
    'Juggler',
    'Licensed Driver',
    'Magician',
    'Medical Equipment',
    'Mime',
    'Modeling',
    'Motorcyclist',
    'Orchestral String Instruments',
    'Percussion',
    'Organ',
    'Pilot',
    'Piano',
    'Precision Driver',
    'Sax',
    'Singer',
    'Square Dance Caller',
    'Teleprompter',
    'Stunts',
    'Trombone',
    'Trumpet',
    'Tuba',
    'Ukulele',
    'Ventriloquist',
    'Violin',
    'Vocal Range: Alto',
    'Vocal Range: Bari-Tenor',
    'Vocal Range: Baritone',
    'Vocal Range: Bass',
    'Vocal Range: Mezzo Soprano',
    'Vocal Range: Soprano',
    'Vocal Range: Tenor',
    'Vocal Style: Legit',
    'Vocal Style: Belt',
    'Vocal Style: Rapper',
    'Voiceover',
    'Whistler'
];

export const ethnicAppearancesMaster = [
    'African',
    'American Indian',
    'African American',
    'Asian',
    'Caucasian',
    'East Indian',
    'Eastern European',
    'Filipino',
    'Hispanic',
    'Mediterranean',
    'Middle Eastern',
    'Multiracial',
    'Pacific Islander',
    'West Indies/Caribbean'
];

export const languagesMaster = [
    'Afrikaans',
    'Arabic',
    'Armenian',
    'Bengali',
    'Bulgarian',
    'Cantonese',
    'Chinese',
    'Danish',
    'Dutch',
    'Farsi',
    'Filipino',
    'French',
    'French Canadian',
    'German',
    'Greek',
    'Hebrew',
    'Hindi',
    'Hungarian',
    'Indonesian',
    'Italian',
    'Japanese',
    'Korean',
    'Latin',
    'Lithuanian',
    'Mandarin',
    'Norwegian',
    'Pashtu',
    'Persian',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Romanian',
    'Sign Language',
    'Russian',
    'Sotho',
    'Spanish',
    'Spanish - Mexico City',
    'Swahili',
    'Swedish',
    'Taiwanese',
    'Thai',
    'Turkish',
    'Urdu',
    'Vietnamese',
    'Yiddish',
    'Xhosa',
    'Zulu'
];

export const accentsMaster = [
    'African',
    'Asian',
    'Asian - Chinese',
    'Asian - Japanese',
    'Asian - Korean',
    'Australian',
    'Boston',
    'British - BBC English',
    'British - Birmingham',
    'British - Cockney',
    'British - Geordie',
    'British - Scouse/Liverpool',
    'British - Yorkshire',
    'Cajun',
    'Canadian',
    'Cockney',
    'Danish',
    'Dutch',
    'East Indian',
    'East-Bosnian',
    'Eastern European',
    'Filipino',
    'Finland',
    'French',
    'French - Canadian',
    'German',
    'Greek',
    'Hungarian',
    'Iraqi',
    'Irish',
    'Israeli',
    'Jamaican',
    'Italian',
    'Jewish/Yiddish',
    'Kosovo-Resava',
    'Mid-East',
    'Middle Eastern',
    'Midwest',
    'Minnesota',
    'New England',
    'New York',
    'Norwegian',
    'New Zealand',
    'Persian',
    'Philadelphia',
    'Polish',
    'Puerto Rican',
    'Russian',
    'Scandinavian',
    'Scottish',
    'Slavic - South Eastern Bloc',
    'Slovonian',
    'South African',
    'Southern',
    'Spanish',
    'Swedish',
    'Texan',
    'Welsh',
    'West Indian'
];

export const disabilitiesMaster = [
    'Amputee Arm',
    'Amputee Double',
    'Amputee Leg',
    'Amputee Single',
    'Asperger\'s',
    'Autism',
    'Blind or Low Vision',
    'Cerebral Palsy',
    'Deaf or Hard of Hearing',
    'Down syndrome',
    'Intellectual Disability',
    'Little Person',
    'Mobility Disability',
    'Wheelchair User',
    'Cane',
    'Crutches: Forearm',
    'Crutches: Underarm',
    'Leg Braces',
    'Mobility Scooter',
    'Prosthetic Limb: Arm',
    'Prosthetic Limb: Leg',
    'Service Animal',
    'Voice Box: Mechanical Larynx',
    'Walker',
    'Wheelchair: Manual',
    'Wheelchair: Power',
    'White Cane'
];

export const genders = [
    { label: 'Select', value: '' },
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
];
export const eyeColorsMaster = [
    { label: 'Select', value: '' },
    { label: 'Amber', value: 'Amber' },
    { label: 'Blue', value: 'Blue' },
    { label: 'Brown', value: 'Brown' },
    { label: 'Gray', value: 'Gray' },
    { label: 'Green', value: 'Green' },
    { label: 'Hazel', value: 'Hazel' },
    { label: 'Red', value: 'Red' },
    { label: 'Violet', value: 'Violet' },
];


export const heightInFeetArray = [
    { label: 'Select', value: '' },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 }
];

export const heightInInchesArray = [
    { label: 'Select', value: '' },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 },
    { label: '10', value: 10 },
    { label: '11', value: 11 },

];

export const typeOfListingsMaster = [
    { label: 'Select', value: '' },
    { label: 'Personal Business', value: 'Personal Business' },
    { label: 'Public Company', value: 'Public Company' },
    { label: 'Enterprise School', value: 'Enterprise School' },
    { label: 'Other', value: 'Other' },
];

export const experianceTypeMaster = [
    { label: 'Select', value: '' },
    { label: 'Theatre experience', value: 'theatreexperience' },
    { label: 'Film experience', value: 'filmexperience' },
    { label: 'TV experience', value: 'tvexperience' },
    { label: 'Education/training', value: 'educationaltraining' },
];

export const hairColorAndTypeArray = [
    { label: 'Select', value: '' },
    { label: 'Auburn', value: 'Auburn' },
    { label: 'Bald', value: 'Bald' },
    { label: 'Black', value: 'Black' },
    { label: 'Gray', value: 'Gray' },
    { label: 'Red', value: 'Red' },
    { label: 'White', value: 'White' },
    { label: 'Salt and Pepper', value: 'Salt and Pepper' },
    { label: 'Blonde (Dark)', value: 'Blonde (Dark)' },
    { label: 'Blonde (Light)', value: 'Blonde (Light)' },
    { label: 'Brown (Dark)', value: 'Brown (Dark)' },
    { label: 'Brown (Light)', value: 'Brown (Light)' },
    { label: 'Blonde (Medium)', value: 'Blonde (Medium)' },
    { label: 'Blonde (Platinum)', value: 'Blonde (Platinum)' },
    { label: 'Blonde (Strawberry)', value: 'Blonde (Strawberry)' },
       
];

export const hairLengthArray = [
    { label: 'Select', value: '' },
    { label: 'Afro', value: 'Afro' },
    { label: 'Long', value: 'Long' },
    { label: 'Receding', value: 'Receding' },
    { label: 'Short', value: 'Short' },
    { label: 'Shoulder Length', value: 'Shoulder Length' },
    { label: 'Bald (On Top)', value: 'Bald (On Top)' },
    { label: 'Bald (Totally)', value: 'Bald (Totally)' },
];
