/**
 * Define all the constants required in application inside this file and export them
 */

export const MAX_TIMEOUT = 10000; // 1000 = 1sec
//
export const FETCH_USER_DATA = 'FETCH_USER_DATA';

// MEMEBR ROLE ASSIGNED CONSTANT 

export const CHANGE_ROLE = 1;
export const REMOVE_FROM_GROUP = 3;
export const ROLE_ADMIN = 'Admin';
export const ROLE_MEMBER = 'Member';
export const AMP_SUPER_ADMIN = 'Super Admin';

// Fetch master Data
export const FETCH_MATER_DATA_SUCCESS = 'FETCH_MATER_DATA_SUCCESS';
export const FETCH_MATER_DATA_FAILURE = 'FETCH_MATER_DATA_FAILURE';
export const FETCH_MATER_DATA_REQUEST = 'FETCH_MATER_DATA_REQUEST';

// COMMAN API CONSTANT
export const API_REQUEST = 'API_REQUEST';
export const API_FAILURE = 'API_FAILURE';

// AUTH API CONSTANT 
export const AUTH_API_REQUEST = 'AUTH_API_REQUEST';
export const AUTH_API_FAILURE = 'AUTH_API_FAILURE';
export const AUTH_LOGOUT_API_REQUEST = 'AUTH_LOGOUT_API_REQUEST';

//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//LogOut
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//UPDATE PASSWORD
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';

// MEMBER SUCCESS

export const MEMBER_SUCCESS = 'MEMBER_SUCCESS';
export const MEMBER_FAILURE = 'MEMBER_FAILURE';

// ORGANISATION SUCCESS
export const ORGANISATION_API_SUCCESS = 'ORGANISATION_API_SUCCESS';


//Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

//Forgot Password
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';


//USER PROFILE VIEW
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';


//Form data 
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';

// Update User Profile
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

//Delete user media 
export const DELETE_USER_MEDIA_SUCCESS = 'DELETE_USER_MEDIA_SUCCESS';

//Post User Media
export const POST_USER_MEDIA_SUCCESS = 'POST_USER_MEDIA_SUCCESS';

// FOR  PRODUCTION PROFILE & HEADSHOT IMAGE
export const PRODUCTION_PROFILE_IMAGE_SUCCESS = 'PRODUCTION_PROFILE_IMAGE_SUCCESS';
export const PRODUCTION_HEADSHOT_IMAGE_SUCCESS = 'PRODUCTION_HEADSHOT_IMAGE_SUCCESS';

// UPDATE USER PRODUCTION DETAIL
export const UPDATE_USER_PRODUCTION_DETAIL_SUCCESS = 'UPDATE_USER_PRODUCTION_DETAIL_SUCCESS';

// SET PROFILE PICTURE

export const SET_PROFILE_PICTURE_SUCCESS = 'SET_PROFILE_PICTURE_SUCCESS';

// GET SITE DATA
export const SITE_API_REQUEST = 'SITE_API_REQUEST';
export const SITE_API_FAILURE = 'SITE_API_FAILURE';
export const GET_SITE_DATA_SUCCESS = 'GET_SITE_DATA_SUCCESS';

// GET ALL ORGANISATION DATA
export const ORGANISATION_API_REQUEST = 'ORGANISATION_API_REQUEST';
export const ORGANISATION_API_FAILURE = 'ORGANISATION_API_FAILURE';
export const GET_ALL_ORGANISATION_DATA_SUCCESS = 'GET_ALL_ORGANISATION_DATA_SUCCESS';

// UPDATE ORGANISATION SUCCESS
export const UPDATE_ORGANISATION_SUCCESS = 'UPDATE_ORGANISATION_SUCCESS';
export const USER_ORGANISATION_IMAGE_SUCCESS = 'USER_ORGANISATION_IMAGE_SUCCESS';
// GET SITE ASSEST BY ID  SUCCESS 
export const GET_SITE_ASSETS_SUCCESS = 'GET_SITE_ASSETS_SUCCESS';

// GET ORGANIZATION MEMBER
export const GET_ORGANISATION_MEMBER_SUCCESS = 'GET_ORGANISATION_MEMBER_SUCCESS';

//INVITE ORGANISATION MEMBER SUCCESS
export const INVITE_ORGANISATION_MEMBER_SUCCESS = 'INVITE_ORGANISATION_MEMBER_SUCCESS';

// UPDATE ORGANISATION MEMBER ROLE SUCCESS 
export const UPDATE_ORGANISATION_MEMBER_ROLE_SUCCESS = 'UPDATE_ORGANISATION_MEMBER_ROLE_SUCCESS';

// GET ORGANISATION ROLES SUCCESS
export const GET_ORGANISATION_ROLES_SUCCESS = 'GET_ORGANISATION_ROLES_SUCCESS';
export const GET_ORGANISATION_MEMBER_COUNT_SUCCESS = 'GET_ORGANISATION_MEMBER_COUNT_SUCCESS';

//GET ASSET PARAMETER AND LIGHT ON/FF/RESET
export const ASSET_PARAMETER_SUCCESS = 'ASSET_PARAMETER_SUCCESS';
export const GET_ASSETS_LIGHT_ON_SUCCESS = 'GET_ASSETS_LIGHT_ON_SUCCESS';
export const GET_ASSET_LIGHT_OFF_OR_RESET_SUCCESS = 'GET_ASSET_LIGHT_OFF_OR_RESET_SUCCESS';
export const DEVICE_LOADER_EVENT = 'DEVICE_LOADER_EVENT';
export const DEVICE_MODEL_POPUP_EVENT = 'DEVICE_MODEL_POPUP_EVENT';
export const DEVICE_STATUS_EVENT = 'DEVICE_STATUS_EVENT';

// GET SITE DEVICES SUCCESS 
export const GET_SITE_DEVICES_SUCCESS = 'GET_SITE_DEVICES_SUCCESS';
export const DEVICE_ON_OFF_EVENT = 'DEVICE_ON_OFF_EVENT';
export const UPDATE_DEVICE_STATUS = 'UPDATE_DEVICE_STATUS';

// GET SINGLE DEVICE SUCCESS 
export const GET_SINGLE_DEVICE_SUCCESS = 'GET_SINGLE_DEVICE_SUCCESS';

// COMMAN DEVICES API CONSTANT
export const DEVICES_API_REQUEST = 'DEVICES_API_REQUEST';
export const DEVICES_API_FAILURE = 'DEVICES_API_FAILURE';

//OPEN CLOSE SITE SUCCESS

export const OPEN_CLOSE_SITE_SUCCESS = 'OPEN_CLOSE_SITE_SUCCESS';

// SET SITE OFF TIME SUCCESS
export const SET_SITE_OFF_TIME_SUCCESS = 'SET_SITE_OFF_TIME_SUCCESS';

// OPEN CLOSE DEVICE SUCCESS

export const OPEN_CLOSE_DEVICE_SUCCESS = 'OPEN_CLOSE_DEVICE_SUCCESS';

// GET ORGANISATION DETAIL SUCCESS 
export const USER_PROFILE_IMAGE_SUCCESS = 'USER_PROFILE_IMAGE_SUCCESS';
export const GET_ORGANISATION_DETAIL_SUCCESS = 'GET_ORGANISATION_DETAIL_SUCCESS';
